---
# Credits to sonroyaalmerol
name: Release Image
on:
  push:
    paths: ['Dockerfile']
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  release:
    name: Release - Docker image
    runs-on: ARM64
    steps:
      - name: Get current date
        id: current-date
        run: |
          echo "TODAY=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          file: Dockerfile
          push: true
          tags: lambor590/SteamCMD_Pterodactyl_arm64:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max